debug: false
receiveProxyProtocol: false
useRedisConfigs: false
useAPIConfigs: true
underAttack: false
connectionThreshold: 50
trackBandwidth: false
prometheus:
  enabled: true
  bind: :9070
api:
  enabled: true
  endpoint: http://brussels.app.coritan.com:4000/dns/srv-records
restapi:
  enabled: true
  bind: 0.0.0.0:3000
mojangAPIenabled: false
geoip:
  enabled: false
  databaseFile:
  enableIprisk: false
redis:
  host: localhost
  pass:
  db: 0
configredis:
  host: localhost
  pass:
  db: 0
rejoinMessage: Please rejoin your server to verify your connection.
blockedMessage: Your connection has been blocked, Please turn off your VPN.
genericJoinResponse: There is no active server for this address. Please contact your administrator.
genericping:
  version: MCServerHost
  description: \u00a7c\u00a7l\u2718 Server Not Found\u00a7r\n\u00a77\u00a7oDouble\u2011check the IP address and try reconnecting
  iconPath: ./server-icon.png
tableflip:
  enabled: false
  pidfile: infrared.pid