debug: false
receiveProxyProtocol: false
useRedisConfigs: false
underAttack: false
connectionThreshold: 50
trackBandwidth: false
prometheus:
  enabled: false
  bind: :9070
api:
  enabled: false
  bind: :5000
mojangAPIenabled: false
geoip:
  enabled: false
  databaseFile:
  enableIprisk: false
redis:
  host: localhost
  pass:
  db: 0
configredis:
  host: localhost
  pass:
  db: 0
rejoinMessage: Please rejoin your server to verify your connection.
blockedMessage: Your connection has been blocked, Please turn off your VPN.
genericJoinResponse: There is no active server for this address. Please contact your administrator.
genericping:
  version: MCSH LImited
  description: There is no server available. Please check your dashboard.
  iconPath: ./server-icon.png
tableflip:
  enabled: false
  pidfile: infrared.pid